
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon May 29 17:21:39 CEST 2017
//----------------------------------------------------

package minijava;

/** CUP generated class containing symbol constants. */
public class Parser_sym {
  /* terminals */
  public static final int DIVIDE = 37;
  public static final int LBRACKET = 8;
  public static final int CHAR = 5;
  public static final int ASSIGNMENT = 38;
  public static final int INV = 41;
  public static final int LPAREN = 12;
  public static final int INT = 3;
  public static final int PRINTLN = 20;
  public static final int MINUS = 35;
  public static final int LESS = 33;
  public static final int STATIC = 27;
  public static final int RPAREN = 13;
  public static final int LCURL = 10;
  public static final int SEMICOLON = 15;
  public static final int AND = 32;
  public static final int BOOL = 4;
  public static final int COMMA = 14;
  public static final int CLASS = 25;
  public static final int PLUS = 34;
  public static final int MAIN = 29;
  public static final int IF = 17;
  public static final int THIS = 23;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int RBRACKET = 9;
  public static final int TRUE = 39;
  public static final int UNARY_PLUS = 42;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int VOID = 28;
  public static final int RCURL = 11;
  public static final int TIMES = 36;
  public static final int ELSE = 18;
  public static final int WHILE = 19;
  public static final int PUBLIC = 26;
  public static final int INTTYPE = 7;
  public static final int EXTENDS = 30;
  public static final int STRING = 6;
  public static final int FALSE = 40;
  public static final int UNARY_MINUS = 43;
  public static final int PRINT = 21;
  public static final int LENGTH = 22;
  public static final int IDENTIFIER = 2;
}

