
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon May 08 17:13:57 CEST 2017
//----------------------------------------------------

package straightline;

/** CUP generated class containing symbol constants. */
public class Parser_sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int LBRACKET = 8;
  public static final int CHAR = 5;
  public static final int INV = 39;
  public static final int LPAREN = 12;
  public static final int INT = 3;
  public static final int PRINTLN = 19;
  public static final int LESS = 31;
  public static final int MINUS = 33;
  public static final int STATIC = 26;
  public static final int RPAREN = 13;
  public static final int LCURL = 10;
  public static final int SEMICOLON = 15;
  public static final int AND = 30;
  public static final int BOOL = 4;
  public static final int COMMA = 14;
  public static final int CLASS = 24;
  public static final int PLUS = 32;
  public static final int MAIN = 28;
  public static final int IF = 17;
  public static final int THIS = 22;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RBRACKET = 9;
  public static final int TRUE = 37;
  public static final int NEW = 23;
  public static final int error = 1;
  public static final int VOID = 27;
  public static final int EQ = 36;
  public static final int RCURL = 11;
  public static final int TIMES = 34;
  public static final int WHILE = 18;
  public static final int PUBLIC = 25;
  public static final int INTTYPE = 7;
  public static final int EXTENDS = 29;
  public static final int STRING = 6;
  public static final int FALSE = 38;
  public static final int PRINT = 20;
  public static final int LENGTH = 21;
  public static final int IDENTIFIER = 2;
}

